

---

- name: sample
  hosts: webserver
  tasks:
   - name: update and upgrade
     become: true
     apt:
       upgrade: yes
       update_cache: yes
   - name: install webserver
     apt: 
       name: apache2
       state: present
   - name: start webserver
     apt: 
       name: apache2
       state: present
   - name: install php
     apt: 
      name: php7.2
      state: present 
   - name: create phpinfo file
     file:
       path: "/var/www/html/info.php"
       state: touch
       owner: www-data     
   - name: write phpinfo to info.php file
     lineinfile:
      path: /var/www/html/info.php
      line: <?php phpinfo(); ?>
      create: yes

  handlers:
    - name: restart  apache
      service: 
        name: apache2
        state: restarted 
