

---

- name: sample
  hosts: webserver
  gather_facts: false
  tasks:
   - name: update and upgrade
     become: true
     apt:
       upgrade: 'yes'
       update_cache: yes
   - name: install packages
     apt: 
       name:
         - apache2
         - php7.2
         - git
         - mysql-server
       state: present
       autoclean: yes 
   - name: start webserver
     apt: 
       name: apache2
       state: present
   - name: create phpinfo file
     file:
       path: "/var/www/html/info.php"
       state: touch
       owner: www-data     
   - name: write phpinfo to info.php file
     lineinfile:
      path: /var/www/html/info.php
      line: <?php phpinfo(); ?>
      create: yes

  handlers:
    - name: restart  apache
      service: 
        name: apache2
        state: restarted 
